# frontend/Dockerfile.dev
FROM node:22-alpine

WORKDIR /usr/src/app

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli@20

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos todas las dependencias
RUN npm install

# Copiamos el código fuente
COPY . .

# Exponemos el puerto
EXPOSE 4200

# Comando para desarrollo
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000", "--disable-host-check"]
