# frontend/Dockerfile.dev
FROM node:22-alpine

WORKDIR /usr/src/app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos todas las dependencias
RUN npm install

# Copiamos el código fuente
COPY . .

# Exponemos el puerto
EXPOSE 4200

# Comando para desarrollo
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
