# frontend/nginx.conf
server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html index.htm;

  location / {
    # Esta línea es clave para las SPAs.
    # Si no se encuentra un archivo, sirve index.html en su lugar.
    try_files $uri $uri/ /index.html;
  }
}
