# api/Dockerfile.dev
FROM node:22-alpine

WORKDIR /usr/src/app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos todas las dependencias (incluyendo dev)
RUN npm install

# Copiamos el código fuente
COPY . .

# Exponemos el puerto
EXPOSE 3000

# Comando para desarrollo con nodemon
CMD ["npm", "run", "dev"]
